version: '3.8'

services:
  leadflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadflow-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_N8N_WEBHOOK_URL=${VITE_N8N_WEBHOOK_URL}
      - VITE_APP_ENV=production
      - VITE_DEBUG_MODE=false
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    networks:
      - leadflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: leadflow-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-servla.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - leadflow
    networks:
      - leadflow-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Monitoramento com Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: leadflow-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - leadflow-network

  # Grafana para visualização
  grafana:
    image: grafana/grafana:latest
    container_name: leadflow-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - leadflow-network

  # Backup automático
  backup:
    image: alpine:latest
    container_name: leadflow-backup
    restart: "no"
    volumes:
      - ./backups:/backups
      - leadflow_data:/app-data
    command: |
      sh -c "
        apk add --no-cache tar gzip
        while true; do
          echo 'Iniciando backup...'
          tar -czf /backups/leadflow-backup-$(date +%Y%m%d_%H%M%S).tar.gz /app-data
          echo 'Backup concluído'
          sleep 86400
        done
      "
    networks:
      - leadflow-network

volumes:
  prometheus_data:
  grafana_data:
  leadflow_data:

networks:
  leadflow-network:
    driver: bridge























